[package]
name = "blackbird"
version = "0.1.0"
authors = ["Conor Hoekstra"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nofmt = "1.0"
